services:
  postgres:
    container_name: postgres-sql-todo
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: todo_app
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - todo-app
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - todo-app
    command:
      - "start-dev"
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chat_db
    volumes:
      - ./mongo-init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_data:/data/db
    networks:
      - todo-app
    restart: unless-stopped
networks:
  todo-app:
    driver: bridge

volumes:
  postgres:
    driver: local
  mongodb_data:
    driver: local