services:
  postgres:
    container_name: postgres-sql-todo
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: todo_app
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - todo-app
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - todo-app
    command:
      - "start-dev"
networks:
  todo-app:
    driver: bridge

volumes:
  postgres:
    driver: local